import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from 'styles/Home.module.scss'
import Message from '../components/message-me/message';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="container">
  <div id="left">
    <h1 id="welcome">Welcome</h1>
    <p id="lorem">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit.<br/>
      Vivamus sodales eros non arcu pellentesque convallis.<br/>
      Nunc dignissim lectus in malesuada porta.<br/>
      Proin ac erat sed urna congue suscipit.<br/>
      Morbi aliquet eget nisl id ornare.
    </p>
  </div>
  <div id="right">
    <h1 id="login">LogIn</h1><br/>
    <input type="email" id="email" className="client-info"/>
    <label  >Email</label>
    <input type="password" id="password" className="client-info"/>
    <label >Password</label>
    <Link href="/onboarding/profile">
    <input type="submit" id="submit" className="client-info" value="Submit"/>
    </Link>
    {/* <button className="social" id="facebook">connect with facebook</button>
    <button className="social" id="google">connect with google</button> */}
  </div>
</div>

     
    

    </div>
  )
}

export default Home
